#include "dialect/oracle_dialect.h"

#ifdef CPPLINQ_HAS_ORACLE

namespace cpplinq {

std::string OracleDialect::quote_id(std::string_view id) const {
    std::string quoted = "\"";
    for (char c : id) {
        if (c == '"') {
            quoted += "\"\"";
        } else {
            quoted += c;
        }
    }
    quoted += "\"";
    return quoted;
}

std::string OracleDialect::placeholder(size_t /*index*/) const {
    return "?";
}

std::string OracleDialect::limit_offset(std::optional<size_t> limit,
                                        std::optional<size_t> offset) const {
    std::string result;
    if (offset.has_value() && limit.has_value()) {
        result = " OFFSET " + std::to_string(*offset) + " ROWS FETCH NEXT " + std::to_string(*limit) + " ROWS ONLY";
    } else if (offset.has_value()) {
        result = " OFFSET " + std::to_string(*offset) + " ROWS";
    } else if (limit.has_value()) {
        result = " OFFSET 0 ROWS FETCH NEXT " + std::to_string(*limit) + " ROWS ONLY";
    }
    return result;
}

std::string OracleDialect::type_name(SqlType type) const {
    switch (type) {
        case SqlType::Integer:        return "NUMBER(10)";
        case SqlType::BigInt:         return "NUMBER(19)";
        case SqlType::UnsignedBigInt: return "NUMBER(20, 0)";
        case SqlType::Real:           return "DOUBLE PRECISION";
        case SqlType::Decimal:        return "NUMBER(28, 10)";
        case SqlType::Text:           return "VARCHAR2(255)";
        case SqlType::WString:        return "NVARCHAR2(255)";
        case SqlType::Blob:           return "BLOB";
        case SqlType::Boolean:        return "NUMBER(1)";
        case SqlType::Date:           return "DATE";
        case SqlType::Time:           return "VARCHAR2(20)";
        case SqlType::Timestamp:      return "TIMESTAMP";
        case SqlType::Interval:       return "VARCHAR2(100)";
        case SqlType::Guid:           return "VARCHAR2(36)";
    }
    return "VARCHAR2(255)";
}

std::string OracleDialect::auto_increment_type() const {
    return "NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY";
}

std::string OracleDialect::returning_clause(std::string_view /*column*/) const {
    return "";
}

std::string OracleDialect::output_clause(std::string_view /*column*/) const {
    return "";
}

std::string OracleDialect::last_insert_id_query(std::string_view table_name, std::string_view pk_col) const {
    if (!table_name.empty() && !pk_col.empty()) {
        return "SELECT NVL(MAX(" + quote_id(pk_col) + "), 0) FROM " + quote_id(table_name);
    }
    return "SELECT 0 FROM DUAL";
}

std::string OracleDialect::create_table_prefix(std::string_view table_name) const {
    return "CREATE TABLE IF NOT EXISTS " + quote_id(table_name);
}

std::string OracleDialect::function_name(std::string_view func) const {
    return std::string(func);
}

std::string OracleDialect::current_timestamp_func() const {
    return "CURRENT_TIMESTAMP";
}

std::string OracleDialect::current_date_func() const {
    return "CURRENT_DATE";
}

std::string OracleDialect::extract_part_func(std::string_view part, std::string_view expr_sql) const {
    return "EXTRACT(" + std::string(part) + " FROM TO_TIMESTAMP(SUBSTR(" + std::string(expr_sql) + ", 1, 19), 'YYYY-MM-DD HH24:MI:SS'))";
}

std::string OracleDialect::date_add_days_func(std::string_view expr_sql, std::string_view days_sql) const {
    return "(TO_TIMESTAMP(SUBSTR(" + std::string(expr_sql) + ", 1, 19), 'YYYY-MM-DD HH24:MI:SS') + NUMTODSINTERVAL(" + std::string(days_sql) + ", 'DAY'))";
}

std::string OracleDialect::generate_upsert(
    std::string_view table_name,
    const std::vector<std::string>& insert_columns,
    const std::vector<std::string>& conflict_columns,
    const std::vector<std::string>& update_columns
) const {
    std::vector<BoundValue> empty_values;
    return generate_upsert(table_name, insert_columns, empty_values, conflict_columns, update_columns);
}

std::string OracleDialect::generate_upsert(
    std::string_view table_name,
    const std::vector<std::string>& insert_columns,
    const std::vector<BoundValue>& /*values*/,
    const std::vector<std::string>& conflict_columns,
    const std::vector<std::string>& update_columns
) const {
    std::string sql = "MERGE INTO " + quote_id(table_name) + " target USING (SELECT ";
    for (size_t i = 0; i < insert_columns.size(); ++i) {
        if (i > 0) sql += ", ";
        sql += placeholder(i) + " AS " + quote_id(insert_columns[i]);
    }
    sql += " FROM DUAL) source ON (";
    for (size_t i = 0; i < conflict_columns.size(); ++i) {
        if (i > 0) sql += " AND ";
        sql += "target." + quote_id(conflict_columns[i]) + " = source." + quote_id(conflict_columns[i]);
    }
    sql += ") WHEN MATCHED THEN UPDATE SET ";
    for (size_t i = 0; i < update_columns.size(); ++i) {
        if (i > 0) sql += ", ";
        sql += "target." + quote_id(update_columns[i]) + " = source." + quote_id(update_columns[i]);
    }
    sql += " WHEN NOT MATCHED THEN INSERT (";
    for (size_t i = 0; i < insert_columns.size(); ++i) {
        if (i > 0) sql += ", ";
        sql += quote_id(insert_columns[i]);
    }
    sql += ") VALUES (";
    for (size_t i = 0; i < insert_columns.size(); ++i) {
        if (i > 0) sql += ", ";
        sql += "source." + quote_id(insert_columns[i]);
    }
    sql += ")";
    return sql;
}

} // namespace cpplinq

#endif // CPPLINQ_HAS_ORACLE
